
settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: true
  open: false
  host: localhost
  port: 5001
schema:
- name: server
  path: ./cmd
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    ignored_paths:
    - .git
    - .idea
    - vendor