version: '3'

volumes:
  db: {}

services:
  db:
    image: mysql
    container_name: go_db
    restart: always
    ports:
      - "3306:3306"
    environment:
       MYSQL_USER: dev
       MYSQL_PASSWORD: password
       MYSQL_DATABASE: storefront
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"